//2014B4A70867P Karan Makhija
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <math.h>

#include "typecheck.h"

//extern int parsecount;
//extern int astcount;

int main(int argc,char *argv[])
{

	if(argc!=3)
	{
		printf("Error: Number of arguments are not correct\n");
		exit(0);
	}

	LoadGrammar("mygrammar.txt");
	computeFirst();
	//printFirst();
	computeFollow();
	//printFollow();
	computeParseTable();
	//printParseTable();
	ParseTreeNode * parseRoot;
	AstNode * astRoot;

	HashTree * mainroot = (HashTree *)malloc(sizeof(HashTree));
	strcpy(mainroot->func,"_main");
	mainroot->sscope = -1;
	mainroot->escope = -1;
	mainroot->inode = NULL;
	mainroot->onode = NULL;
	mainroot->child = NULL;
	mainroot->parent = NULL;
	mainroot->link = NULL;
	mainroot->ptr = createHashTable();

	printf("LEVEL 1:Symbol table/ AST/ TypeChecking/ Semantic Rules modules work.\n");
	int option;

	

	printf("Press Option for the defined task\n");
	printf("0:For exiting\n");
	printf("1:For printing  of tokens generated by lexer\n");
	printf("2:For parsing to verify the syntactic correctness and print parseTree\n");
	printf("3:For printing Abstract Syntax Tree\n");
	printf("4:For allocated memory and number of nodes for AST and ParseTree\n");
	printf("5:For printing symbol Table\n");
	printf("6:For checking syntactic and semantic correctness\n");
	printf("7:For producing assembly code\n");

	int errorflag = 0;
	scanf(" %d",&option);
		
	switch(option)
	{
		case 0: break;
		case 1: printListOfTokens(argv[1]);
			break;
		case 2: parseRoot = parseInputSourceCode(argv[1],&errorflag);
			if(errorflag == 0)
			printf("Input source code is syntactically correct...........\n");
			printParseTree(parseRoot,argv[2]);
			
			break; 
		case 3:	parseRoot = parseInputSourceCode(argv[1],&errorflag);
			//printParseTree(parseRoot,argv[2]);
			astRoot = constructAstTree(parseRoot,NULL);
			printf("Traversal order: Inorder\n");
			printAst(astRoot);
			break;
		case 4: parseRoot = parseInputSourceCode(argv[1],&errorflag);
			//printParseTree(parseRoot,argv[2]);
			astRoot = constructAstTree(parseRoot,NULL);
			//printAst(astRoot);
			printParseCount();
			printAstCount();
			break;
		case 5:
			parseRoot = parseInputSourceCode(argv[1],&errorflag);
			//printParseTree(parseRoot,argv[2]);
			astRoot = constructAstTree(parseRoot,NULL);
			//printAst(astRoot);
			mainroot = addEntriesAndTypeCheck(astRoot,mainroot);
			printSymboltable(mainroot,1);
			break;
		case 6:
			parseRoot = parseInputSourceCode(argv[1],&errorflag);
			//printParseTree(parseRoot,argv[2]);
			if(errorflag == 0)
			{
				printf("Input source code is syntactically correct...........\n");
				astRoot = constructAstTree(parseRoot,NULL);
				//printAst(astRoot);
				mainroot = addEntriesAndTypeCheck(astRoot,mainroot);
				mainroot = typeCheck(astRoot,mainroot);

			}
			else
			{
				printf("Input source code is syntactically incorrect...........\n");
				
			}	
			
			break;
		case 7:
			printf("Not implemented\n");
			break; 

		default:printf("Invalid option. Enter again");
	}
		

		

	return 0;

}